name: "Configure scripts"

on:
  push:
    branches:
      - main

jobs:
  configure-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for non-Unix line endings
        id: check_line_endings
        run: |
          if grep -rIl $'\r' scripts/; then
            echo "NEEDS_CONVERSION=true" >> $GITHUB_ENV
          else
            echo "NEEDS_CONVERSION=false" >> $GITHUB_ENV
          fi
      
      - name: Install dos2unix and convert line endings
        if: env.NEEDS_CONVERSION == 'true'
        run: |
          sudo apt-get update -y
          sudo apt-get install dos2unix -y
          sudo dos2unix scripts/*
          chmod 755 scripts/*

      - name: Add, commit, and push changes
        id: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add scripts/*
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Configure scripts"
            git push origin main
          fi
