name: "Configure scripts"

on:
  push:
    branches:
      - main

jobs:
  configure-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure scripts
        run: |
          sudo apt-get update -y
          sudo apt-get install dos2unix -y
          sudo dos2unix scripts/*
          chmod 755 scripts/*

      - name: Add, commit, and push changes
        id: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add scripts/*
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "COMMIT_PUSHED=false" >> $GITHUB_ENV
          else
            git commit -m "Configure scripts"
            git push origin main
            echo "COMMIT_PUSHED=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Configure scripts"
          branch: "configure-scripts-branch"
          push-to-fork: "MiguelRodo/dotfiles"
          title: "Automated Pull Request to Configure Scripts"
          body: "This PR is automatically created by GitHub Actions to configure scripts."
          base: "main"