name: Update Fork

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-miguelrodo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          repository: MiguelRodo/dotfiles  # Check out your fork repository
          token: ${{ secrets.MIGUELRODOPAT }}  # Use your PAT for authentication

      - name: Install GitHub CLI if not available
        run: |
          if ! command -v gh &> /dev/null; then
            echo "gh could not be found, installing..."
            sudo apt-get update
            sudo apt-get install gh -y
          else
            echo "gh is already installed"
          fi

      - name: Create New Branch for Merging
        run: |
          echo "Triggering change"
          git checkout -b merged-changes-satvilab main  # Create a new branch 'merged-changes-satvilab' from the fork's main branch

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/SATVILab/dotfiles.git  # Add the upstream repository
          git fetch upstream main  # Fetch the upstream main branch

      - name: Merge New Branch with Upstream
        run: |
          git merge -X theirs upstream/main || echo "Automatic merge failed, manual intervention required!" > merge_status.txt  # Merge upstream's 'main' into 'merged-changes-satvilab', favoring upstream changes

      - name: Commit Changes
        if: success()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Merge upstream changes and resolve conflicts favoring upstream" || echo "No changes to commit"

      - name: Check for Merge Conflicts
        run: |
          if [ -f merge_status.txt ]; then
            echo "Merge conflicts detected, please resolve manually."
            exit 1
          fi

      - name: Push the New Branch to Fork
        if: success()
        run: |
          git push --force origin merged-changes-satvilab  # Push the new branch with the merged changes to your fork

      - name: Check for differences
        run: |
          git fetch origin main
          if git diff --exit-code main..HEAD; then
            echo "No differences between branches."
            echo "NO_DIFF=true" >> $GITHUB_ENV
          else
            echo "Differences detected."
            echo "NO_DIFF=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request Using gh CLI
        if: env.NO_DIFF == 'false'
        env:
          GH_TOKEN: ${{ secrets.MIGUELRODOPAT }}  # Use your PAT for authentication
        run: |
          gh pr create \
            --repo MiguelRodo/dotfiles \
            --head merged-changes-satvilab \
            --base main \
            --title "Sync with Upstream" \
            --body "This PR syncs your fork with the upstream repository." \
            --assignee @me
