name: Update Fork

on:
  schedule:
    - cron: '0 0 * * 0'  # Schedule to run every Sunday at midnight
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          repository: MiguelRodo/dotfiles
          token: ${{ secrets.MIGUELRODOPAT }}

      - name: Delete Existing PR Branches
        run: |
          for branch in "merged-changes-satvilab" "unmerged-changes-satvilab"; do
            if git ls-remote --exit-code --heads origin $branch; then
              echo "Deleting existing branch: $branch"
              git push origin --delete $branch
            else
              echo "Branch $branch does not exist."
            fi
          done

      - name: Delete Existing PRs
        run: |
          gh pr list --state open --repo MiguelRodo/dotfiles --json number,headRefName \
            --jq '.[] | select(.headRefName=="merged-changes-satvilab" or .headRefName=="unmerged-changes-satvilab") | .number' |
            xargs -I {} gh pr close {} --repo MiguelRodo/dotfiles

      - name: Create New Branch for Merging
        run: |
          echo "Creating a new branch 'merged-changes-satvilab' from 'main'"
          git checkout -b merged-changes-satvilab main

      - name: Add Upstream Repository
        run: |
          echo "Adding upstream repository and fetching 'main' branch"
          git remote add upstream https://github.com/SATVILab/dotfiles.git
          git fetch upstream main

      - name: Merge Upstream Changes
        run: |
          git checkout -b merged-changes-satvilab
          echo "Attempting to merge 'upstream/main' into 'merged-changes-satvilab'"
          
          # Save the current state
          git diff main > /tmp/before_merge.diff

          # Perform the merge
          git merge -X theirs upstream/main -m "Merged upstream changes, favouring upstream in case of conflicts" || echo "Automatic merge failed, manual intervention required!" > merge_status.txt

          # Check for differences after merge
          git diff main > /tmp/after_merge.diff

      - name: Check Merge Status
        run: |
          # Compare the diff files
          if [ -s /tmp/after_merge.diff ]; then
            echo "Merge introduced changes."
            echo "MERGE_STATUS=changed" >> $GITHUB_ENV
          else
            echo "No changes introduced by merge."
            echo "MERGE_STATUS=unchanged" >> $GITHUB_ENV
          fi

      - name: Handle Merge Conflicts
        run: |
          if [ -f merge_status.txt ]; then
            echo "Merge conflicts detected. Creating branch for manual merge."
            git checkout -b unmerged-changes-satvilab upstream/main
            git push origin unmerged-changes-satvilab
            echo "MERGE_STATUS=manual" >> $GITHUB_ENV
          else
            echo "Merge successful."
            echo "MERGE_STATUS=success" >> $GITHUB_ENV
          fi

      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Merge upstream changes and resolve conflicts favoring upstream" || echo "No changes to commit"

      - name: Push the Merged Branch to Fork
        run: |
          echo "Pushing merged branch 'merged-changes-satvilab' to fork"
          git push --force origin merged-changes-satvilab

      - name: Check for Differences
        run: |
          echo "Checking for differences between 'main' and 'HEAD'"
          git fetch origin main
          echo "Running git diff main..HEAD"
          git diff main..HEAD  # Show the differences
          if git diff --exit-code main..HEAD; then
            echo "NO_DIFF=true" >> $GITHUB_ENV
          else
            echo "NO_DIFF=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request for Successful Merge
        if: ${{ env.NO_DIFF == 'false' && env.MERGE_STATUS == 'success' }}
        run: |
          echo "Creating PR for successful merge"
          echo "Checking for differences using 'git rev-list'"
          git rev-list --left-right --count main...merged-changes-satvilab  # Show the rev-list differences
          if [ "$(git rev-list --count main..merged-changes-satvilab)" -eq 0 ]; then
            echo "No differences found, skipping PR creation."
          else
            gh pr create \
              --repo MiguelRodo/dotfiles \
              --head merged-changes-satvilab \
              --base main \
              --title "Sync with Upstream" \
              --body "This PR syncs your fork with the upstream repository." \
              --assignee @me
          fi
        env:
          GH_TOKEN: ${{ secrets.MIGUELRODOPAT }}

      - name: Create Pull Request for Manual Merge
        if: ${{ env.NO_DIFF == 'false' && env.MERGE_STATUS == 'manual' }}
        run: |
          echo "Creating PR for unsuccessful merge"
          echo "Checking for differences using 'git rev-list'"
          git rev-list --left-right --count main...unmerged-changes-satvilab  # Show the rev-list differences
          if [ "$(git rev-list --count main..unmerged-changes-satvilab)" -eq 0 ]; then
            echo "No differences found, skipping PR creation."
          else
            gh pr create \
              --repo MiguelRodo/dotfiles \
              --head unmerged-changes-satvilab \
              --base main \
              --title "Manual Merge Required: Sync with Upstream" \
              --body "This PR contains upstream changes that could not be merged automatically. Manual resolution is required." \
              --assignee @me
          fi
        env:
          GH_TOKEN: ${{ secrets.MIGUELRODOPAT }}
